name: Build and Release Oreneta ISO

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build ISO and Create Release Assets
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies (Debian-based)
      run: |
        sudo apt update
        sudo apt install -y base-devel nasm xorriso llvm-tools clang grub-common mtools qemu

    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env

    - name: Build ISO
      run: make

    - name: List Generated Files
      run: ls -lah

    - name: Upload ISO as Release Asset
      uses: actions/upload-artifact@v3
      with:
        name: generated-iso
        path: ./oreneta.iso # Replace with the actual path to your ISO
