name: Build ISO on Commit

on:
  push:
    branches:
      - '**' # Triggers on any branch push. Adjust to target specific branches if needed.

jobs:
  build:
    name: Build ISO
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies (Debian-based)
      run: |
        sudo apt update
        sudo apt install -y build-essential nasm xorriso clang grub-common mtools qemu
        sudo apt install -y llvm clang

    - name: Install Rust and Configure Toolchain
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env
        rustup install nightly-x86_64-unknown-linux-gnu
        rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
        rustup override set nightly

    - name: Build ISO
      run: make

    - name: List Generated Files
      run: ls -lah

    - name: Upload ISO as Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: generated-iso
        path: ./oreneta.iso # Replace with the actual path to the generated ISO
